#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

cat /etc/s6-overlay/s6-rc.d/init-adduser/branding

echo '
https://www.tracelabs.org/

───────────────────────────────────────
GID/UID
───────────────────────────────────────'
echo "
User UID:    $(id -u abc)
User GID:    $(id -g abc)
───────────────────────────────────────
"

lsiown abc:abc /app
lsiown abc:abc /config
lsiown abc:abc /defaults
