name: build-on-commit

on:
  push:
    branches:
      - master

jobs:
  build:
    name: tlosint-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: >
          docker buildx build --push
          --tag ghcr.io/tracelabs/tlosint-docker:$(curl -sX GET "https://api.github.com/repos/tracelabs/tlosint-vm/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')-$(git rev-parse --short HEAD)
          --tag ghcr.io/tracelabs/tlosint-docker:latest .
