name: build-on-commit

on:
  push:
    branches:
      - master

jobs:
  build:
    name: tlosint-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: >
          docker buildx build --push
          --tag ghcr.io/thelamer/tlosint-docker:$(git rev-parse --short HEAD)
          --tag ghcr.io/thelamer/tlosint-docker:latest .
