name: Daily Package check
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  pupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          bash ci-scripts/update-packages.sh
          git config --global user.name 'Package Bot'
          git config --global user.email 'package-bot@users.noreply.github.com'
          git add package_versions.txt
          git diff --quiet HEAD || git commit -m "Bot Updating Package Versions" && git push origin master
